name: Build Go Binary for Ubuntu

on:
  push:
    branches:
      - main  # 触发工作流的分支
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码

      - name: Set up Go
        uses: actions/setup-go@v4  # 设置 Go 环境
        with:
          go-version: '1.21'  # 指定 Go 版本

      - name: Build binary
        run: |
          # 设置输出目录
          mkdir -p dist
          # 编译 Go 项目，生成二进制文件
          GOOS=linux GOARCH=amd64 go build -o dist/ipecho .

      - name: Compress binary
        run: |
          # 使用 gzip 压缩二进制文件
          gzip -9 dist/ipecho

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3  # 上传生成的二进制文件
        with:
          name: ipecho.gz
          path: dist/ipecho.gz